In [1]:
import numpy as np

In [2]:
x = np.array([range(1, 10)])

In [3]:
x

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [5]:
x1 = np.array([range(i, i+10) for i in [2, 3, 4]])
x1

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [6]:
np.random.normal(0, 1, (3, 3))

array([[ 0.94858864,  0.07037914, -1.97050909],
       [-0.43138024,  0.13817993,  1.99906438],
       [ 0.78106829,  0.15487009, -0.71474337]])

In [7]:
np.array([range(i, i+3) for i in [2, 3, 6]])

array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10, (3,3))

TypeError: Cannot interpret '3' as a data type

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.zeros((4,3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [21]:
x1 = np.zeros((3,4))
x1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
x2 = np.ones((3,4))
x2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
x3 = np.dstack([x1, x2])
x3

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])